{
    'words':
        [
            'Analyzation',
            'enormora',
            'linkname',
            'gname',
            'devminor',
            'devmajor',
            'ssri',
            'packtory',
            'subrecord',
            'kleur',
            'cmds'
        ]
}
