---
name: Continuous integration

on:
    push:
    pull_request:
    merge_group:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [24.x, 26.x]
        name: Node.js v${{ matrix.node-version }}
        steps:
            - uses: actions/checkout@v6
            - name: Use Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm clean-install
            - name: Static Code Analysis
              run: npx just lint
            - name: Compile Typescript
              run: npx just compile
            - name: Run tests
              run: npx just test
            - name: Dry-run publish
              run: npx just publish-dry-run
              env:
                  NPM_TOKEN: dry-run

    mutation-testing:
        runs-on: ubuntu-latest
        name: Mutation testing
        steps:
            - uses: actions/checkout@v6
            - name: Use Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 26.x
            - name: Install dependencies
              run: npm clean-install
            - name: Run mutation tests
              run: npx just test-mutation

    benchmarks:
        runs-on: ubuntu-latest
        name: Benchmarks
        steps:
            - uses: actions/checkout@v6
            - name: Use Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 26.x
            - name: Install dependencies
              run: npm clean-install
            - name: Run benchmarks
              run: npx just benchmark
